### PR TITLE
first pull request test by littleflute

### PR DESCRIPTION
**Pull request by littleflute**

### CODE REVIEW

**Comment by littleflute** [comment]
c1

**Comment by jeremyjia** [comment]
xd2

**Comment by jeremyjia** [comment]
aaaaaaaaaaaaa

**Comment by jeremyjia** [comment]
alert(addNewGitHubComment);

**Comment by jeremyjia** [comment]
var s = "test-server.js: v0. 11";
var d = blo0.blMD("id_4-"+s, s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 
var ta = blo0.blGetTa();

x.blr_jeremyjia_Games_issues = function(b,d){ jgis(d); on(b,d);}; x.bll1j = "";
x.blr_getOnlineUser       = function(b,d){ f1(d); on(b,d);}; x.bll1 = "";
x.blr_addNewGitHubComment = function(b,d){ f2(d); on(b,d);}; x.bll2 = "";

x.blrGetGhi = function(b,d){
  x.i =  blo0.blGetGithubIssueByNumber("jeremyjia","Games",1,function(o){
       d.innerHTML = o.comments + blo0.blDate(); 
      
  }); 
}

x.blrGetGhiCs = function(b,d){
   d.innerHTML = blo0.blDate();
   x.i.cs(function(o){
      var tb1 = blo0.blDiv(d,d.id+"tb1","tb1","grey");
      var tb2 = blo0.blDiv(d,d.id+"tb2","tb2","lightblue");
      for(j in o){
          const btn = blo0.blBtn(tb1,tb1.id+j,j,"gray");
          btn .onclick = function(_j){
             return function(){
                 ta.value = o[_j].body;
             }
          }(j);
          const btn2 = blo0.blBtn(tb2,tb2.id+j,j,"green");
          btn2.cid = o[j].id;
          btn2 .onclick = function(_btn2,_j){
             return function(){
                 var testD = ta.value;
                 blo0.blUpdateGithubCommentById("jeremyjia","Games",_btn2.cid,testD,function(res){
                   ta.value = _btn2.cid;
                 });
             }
          }(btn2,j);
      }
   });
}
blo0.blShowObj2Div(d.v,x);
bl$("blr_jeremyjia_Games_issues").click();
bl$("blr_getOnlineUser").click();
_on_off_div(null,d);
 

function jgis(d){
  var tb = blo0.blDiv(d,d.id+"tb","tb",blGrey[0]);
  var tbx2  = blo0.blDiv(d,d.id+"tbx2","tbx2",blGrey[3]);
  var v1  = blo0.blDiv(d,d.id+"v1","v1",blGrey[4]);
  const isStart = ["11-101","11-120","71-80","81-90","91-99"];   

  for(i in isStart){
     var btn = blo0.blBtn(tb,tb.id+i,isStart [i] ,blGrey[1]);
     btn.onclick = function(_thisBtn,_i){
        return function(){
            var a = isStart[_i].split('-');
            tbx2.innerHTML = a; 
            for(var j = a[0]; j <= a[1];j++){
                var btn = blo0.blBtn(tbx2,tbx2.id+j,j ,blGrey[5]);
                btn.onclick = function(_j){
                  return function(){
                    v1.innerHTML = _j;
                  }
                }(j);
            }             
        }
     }(btn,i);
  } 
}
function f2(d){
    var ja = Date();
    addNewGitHubComment(1,ja,function(response){                            
                    if (response.readyState == 4) {
                        if (response.status == 200 || response.status == 201) {
                            d.innerHTML = Date();
                        } else {
                            d.innerHTML = "Errors, status=" + response.status;
                        }
                    }
    }); 
}

function f1(d){
  getOnlineUser(function(j){
     blo0.blShowObj2Div(d,j);
  });
}
function on(b,d){
   _on_off_div(b,d); 
   b.style.background = b.style.background=="red"?blGrey[5]:blColor[4];
}

**Comment by jeremyjia** [comment]
5

**Comment by jeremyjia** [comment]
6

**Comment by jeremyjia** [comment]
7

**Comment by jeremyjia** [comment]
alert(addNewGitHubComment);

**Comment by jeremyjia** [comment]
999999999

**Comment by jeremyjia** [comment]
xd11

**Comment by jeremyjia** [comment]
function(){
  alert(11);
}

**Comment by jeremyjia** [comment]
https://www.w3schools.com/

**Comment by jeremyjia** [comment]
function(){
	var i = 2;
	if(!this.d){
	  this.d = blo0.blMDiv(this.parentElement,"id4_blclass_test","MDivi724",50,50,500,400,"green");
	  var tb = blo0.blDiv(this.d,this.d.id+"tb","tb","gray");
	  var tb1= blo0.blDiv(this.d,this.d.id+"tb1","tb1","lightgray");
	  var v2= blo0.blDiv(this.d,this.d.id+"v2","v2","gray");
	  var tb2= blo0.blDiv(v2,v2+"tb2","tb2","lightgreen");
	  var b1 = blo0.blBtn(tb,tb.id+"b1","i"+i,"brown");
	  b1.onclick = function(){  
		tb.i = blo0.blGetGithubIssueByNumber("jeremyjia","Games",i,function(o){
		   ta.value = JSON.stringify(o);
		});
	  }
	  var b2 = blo0.blBtn(tb,tb.id+"b2","i"+i+"cs","lightblue");
	  b2.onclick = function(){  
		tb.i.cs(function(o){
		   for(j in o){
			 const btn1 = blo0.blBtn(tb1,tb1.id+j,j,"gray");
			 btn1.style.float = "left";
			 const btn2 = blo0.blBtn(tb2,tb2.id+j,j,"gray");
			 btn2.style.float = "left";
			 
			 btn1.btn2 = btn2;
			 btn1.code =  o[j].body;
			 btn1.cid  = o[j].id;
			 btn1.save2gh = function(){
								  if( typeof blo0.blUpdateGithubCommentById == "function"){  
									  blo0.blUpdateGithubCommentById(user,repo,this.cid,this.code,function(r){
										  ta.value = r;
									  }); 
									  var b = bl$(this.btn2.id); 
									  b.onclick = function(_code){
										  var s = "var f = " + _code;
										  eval(s);
										  return f;
									  }(this.code);
									  ta.status (this.id + ": save to i=" + i+ " : c=" + j + " cid="+this.cid);
								  }
								  else{
									  ta.status (this.id + ": can't find function blo0.blUpdateGithubCommentById");
								  }
							  }
			 btn1.onclick = function(_thisBtn,_j){
			   return function(){
				 ta.co = _thisBtn;               
				 ta.value = _thisBtn.code;
			   }
			 }(btn1,j);
		   }
		});
	  }
	  var b3 = blo0.blBtn(tb,tb.id+"b3","+c","green");b3.i = i;
	  b3.onclick = function(_i){  
		 return function(){
			blo0.addNewGitHubComment(_i,ta.value,function readCallBack(resp){
			  if(resp.readyState == 4){
				  if(resp.status==200){
					  ta.value = resp.responseText; 
				  }else{
					  ta.value = resp.responseText + " The status code:"+resp.status ; 
				  }
			  }			 
		});
		};
	  }(i);
	}
	_on_off_div(this,this.d);
	 var b = this;
	 b.style.background = b.style.background=="red"?blGrey[5]:blColor[4];  
}

**Pull request merged**
